name: action workflow

on: [push]

jobs:
    run-github-actions:
        runs-on: ubuntu-latest
        steps:
            - name: want to check Java action
              id: hello
              uses: actions/hello-world-javascript-action@v1
              with:
                who-to-greet: Good Afternoon

            - name: Get the output time
              run: echo "${{ steps.hello.outputs.time }}"